name: OPCServer
language: python
variables:
  - name: PASSWORD
    inputType: Secret
    description: Websocket password
    defaultValue: websocket_password
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: websocket-destination
